/**
 * Curated reel topics — randomized, no repeats.
 * Once exhausted, falls back to any unposted lesson.
 */

// Priority topics — these go first, in random order
export const PRIORITY_TOPICS: string[] = [
  'Documentation',
  'Clock Speed, Cores, and Threads',
  'HDD vs SSD Storage',
  'Processes and Threads',
  'The History of Programming Languages',
  'Object-Oriented Programming',
  'Functional Programming',
  'Compilers',
  'Debugging - Finding and Fixing Bugs',
  'Named Tuples',
  'Web Development - Frontend and Backend',
  'Deployment and Hosting',
  'Authentication and Authorization',
  'Variables',
  'Data Types & Type Conversion',
  'User Input',
  'if Statements',
  'elif & else',
  'Nested Conditions',
  'while Loops',
  'for Loops',
  'The range() Function',
  'Variable Arguments (*args)',
  'else in Loops',
  'Creating Functions',
  'Nested Functions',
  'The LEGB Rule',
  'String Indexing & Slicing',
  'String Formatting',
  'f-Strings',
  'Unicode',
  'Exceptions',
  'try / except',
  'else with try / except',
  'finally',
  'raise',
  'Creating Lists',
  'Nested Lists',
  'Tuple Basics',
  'Creating Sets',
  'Set Operations',
  'Frozen Sets',
  'Hashing',
  'Keys & Values',
  'Dictionary Methods',
  'Nested Dictionaries',
  'Creating Modules',
  'Importing Modules',
  'Packages',
  'CSV Files',
  'JSON Files',
  'Classes',
  'Objects',
  'Attributes',
  'Methods',
  'Constructors',
  'Inheritance',
  'Polymorphism',
  'Encapsulation',
  'Abstraction',
  'Composition',
  'Multiple Inheritance',
  'Magic Methods',
  'Lambda Functions',
  'Creating Decorators',
  'The with Statement',
  'Basic Types',
  'Creating Dataclasses',
  'Enum Basics',
  'Regex Syntax',
  'Logging Basics',
  'Unit Testing',
  'pytest',
  'Test Coverage',
  'Test-Driven Development (TDD) Introduction',
  'VS Code Debugger',
  'Breakpoints',
  'Stack Trace',
  'Logging vs Debugging',
  'Common Bugs',
  'Profiling',
  'Time Complexity',
  'Memory Usage',
  'Optimization',
  'Caching',
  'Benchmarking',
  'Threads',
  'Multiprocessing',
  'asyncio',
  'async / await',
  'Synchronization',
  'Versioning',
  'Publishing to PyPI',
  'Python Bytecode',
  'CPython',
  'Garbage Collection',
  'Refactoring',
  'Code Smells',
  'Design Patterns',
  'Production Code',
];
